### ISSUE TITLE
I want to participate in MIUI 9

### ISSUE THREAD

**Issue by BASHEER-A** [ingbrzy/MA-XML-9.0-ARABIC-Global#1]
Hello...
I want to participate in MIUI 9
If possible add me and  g4xl
There are words that need translation

**Comment by ingbrzy** [comment]
Please fix them in crowdin MIUI global translation.. This repository will be always updated by Global ROM translation every week..

**Comment by BASHEER-A** [comment]
Do you mean .. Upload files to crowdin a platform
Then I correct the mistake and then re-upload it here ?

**Comment by ingbrzy** [comment]
No.. Update it on crowdin only.. Then I will pull them from Global ROM and add it here..

**Comment by BASHEER-A** [comment]
Thank you .. This means that I will contribute to Arabization here only https://crowdin.com/project/miui-v6/ar#   .. And you will modify the files .. Thank you again
