### ISSUE TITLE
The Arabic language suffers from a problem 

### ISSUE THREAD

**Issue by BASHEER-A** [ingbrzy/MA-XML-9.0-ARABIC-Global#2]
**Good morning .. The Arabic language suffers from a problem .. The symbol appears instead of the phrase such symbols
.. you need to edit the file, try correcting, but unfortunately I have no validity**

These codes appear only for Arabic

> &amp;#1594;&amp;#1610;&amp;#1585; &amp;#1605;&amp;#1608;&amp;#1580;&amp;#1608;&amp;#1583; &amp;#1601;&amp;#1610; &amp;#1580;&amp;#1607;&amp;#1575;&amp;#1578; &amp;#1575;&amp;#1604;&amp;#1575;&amp;#1578;&amp;#1589;&amp;#1575;&amp;#1604; &amp;#1575;&amp;#1604;&amp;#1582;&amp;#1575;&amp;#1589;&amp;#1577; &amp;#1576;&amp;#1603;.

**Comment by ingbrzy** [comment]
screenshot?

**Comment by BASHEER-A** [comment]
![whatsapp image 2017-08-26 at 3 45 45 am](https://user-images.githubusercontent.com/25770575/29771181-28fa56a2-8bfb-11e7-9dbb-cf84ad459b57.jpeg)

**Comment by ingbrzy** [comment]
Fixed
